### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by Entrebear** [tsvillain/flutter_chip_tags#5]
Is this package going to be updated to work with Null Safety?

**Comment by tsvillain** [comment]
I haven't planned that, but I think this should be Null Safe.
Let me know if you want to work on this issue else I will do this in the next 24 hours.

**Comment by tsvillain** [comment]
@Entrebear Please get the latest version from pub.dev, I have updated the plugin to null safe.

```
dependencies:
  flutter_chip_tags: ^2.0.0
```
