### ISSUE TITLE
Submit with Enter instead of Space

### ISSUE THREAD

**Issue by Entrebear** [tsvillain/flutter_chip_tags#6]
Is it possible to update this package to submit chip with the enter key?

**Comment by tsvillain** [comment]
@Entrebear Just published a new version on pub.dev
I have added a property `createTagOnSubmit` which is by default `false`, if it's true then the plugin will create tags on submit, if both `separator` and  `createTagOnSubmit` are used and `separator` will be ignored.

```
dependencies:
  flutter_chip_tags: ^2.0.1
```
