### ISSUE TITLE
Positioning of chips

### ISSUE THREAD

**Issue by Entrebear** [tsvillain/flutter_chip_tags#8]
Would it be possible to add a property to determine if the chips are above / below the text field?

P.S. Many thanks for the updates you have done, I greatly appreciate it.

**Comment by tsvillain** [comment]
@Entrebear sounds good. I will update the plugin in a few days.
Thanks for the suggestions.

**Comment by tsvillain** [comment]
@Entrebear This feature is added in version v2.0.2
